---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: clustertargets.multicluster.admiralty.io
  labels:
    helm.sh/chart: multicluster-scheduler
spec:
  group: multicluster.admiralty.io
  names:
    kind: ClusterTarget
    plural: clustertargets
    shortNames:
      - ctg
  scope: Cluster
  subresources:
    status: {}
  version: v1alpha1
