apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: clustersummaries.multicluster.admiralty.io
  labels:
    helm.sh/chart: multicluster-scheduler
spec:
  group: multicluster.admiralty.io
  names:
    kind: ClusterSummary
    plural: clustersummaries
    shortNames:
      - mcsum
  scope: Cluster
  subresources:
    status: {}
  version: v1alpha1
