apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: clustersources.multicluster.admiralty.io
  labels:
    helm.sh/chart: multicluster-scheduler
spec:
  group: multicluster.admiralty.io
  names:
    kind: ClusterSource
    plural: clustersources
    shortNames:
      - csrc
  scope: Cluster
  subresources:
    status: {}
  version: v1alpha1
