---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: podchaperons.multicluster.admiralty.io
  labels:
    helm.sh/chart: multicluster-scheduler
spec:
  group: multicluster.admiralty.io
  names:
    kind: PodChaperon
    plural: podchaperons
    shortNames:
      - chap
  scope: Namespaced
  subresources:
    status: {}
  version: v1alpha1
  additionalPrinterColumns:
    - name: reserved
      type: string
      JSONPath: .metadata.annotations.multicluster\.admiralty\.io/is-reserved
    - name: allowed
      type: string
      JSONPath: .metadata.annotations.multicluster\.admiralty\.io/is-allowed
