apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: sources.multicluster.admiralty.io
  labels:
    helm.sh/chart: multicluster-scheduler
spec:
  group: multicluster.admiralty.io
  names:
    kind: Source
    plural: sources
    shortNames:
      - src
  scope: Namespaced
  subresources:
    status: {}
  version: v1alpha1
