apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: targets.multicluster.admiralty.io
  labels:
    helm.sh/chart: multicluster-scheduler
spec:
  group: multicluster.admiralty.io
  names:
    kind: Target
    plural: targets
    shortNames:
      - tg
  scope: Namespaced
  subresources:
    status: {}
  version: v1alpha1
