required = [
  "k8s.io/code-generator/cmd/deepcopy-gen",
  "sigs.k8s.io/controller-tools/cmd/controller-gen"
]

[prune]
  go-tests = true
  unused-packages = true

# For dependency below: Refer to issue https://github.com/golang/dep/issues/1799
[[override]]
  name = "gopkg.in/fsnotify.v1"
  source = "https://github.com/fsnotify/fsnotify.git"
  version="v1.4.7"

# https://github.com/mattbaird/jsonpatch/issues/7
# until https://github.com/kubernetes-sigs/controller-runtime/pull/289 is released
[[override]]
  name = "github.com/mattbaird/jsonpatch"
  source = "https://github.com/appscode/jsonpatch.git"
