apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  labels:
    controller-tools.k8s.io: "1.0"
  name: deploymentdecisions.multicluster.admiralty.io
spec:
  group: multicluster.admiralty.io
  names:
    categories:
    - decisions
    kind: DeploymentDecision
    plural: deploymentdecisions
  scope: Namespaced
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          type: string
        kind:
          type: string
        metadata:
          type: object
        spec:
          properties:
            template:
              properties:
                metadata:
                  type: object
                spec:
                  type: object
              type: object
          required:
          - template
          type: object
        status:
          type: object
  version: v1alpha1
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
