apiVersion: apps/v1
kind: Deployment
metadata:
  name: multicluster-scheduler-agent
spec:
  template:
    spec:
      containers:
      - name: controller
        volumeMounts:
        - name: admiralty
          mountPath: "/var/run/secrets/admiralty.io/serviceaccountimports/CLUSTER_NAME"
          readOnly: true
      volumes:
      - name: admiralty
        secret:
          secretName: admiralty
