apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "fullname" . }}-post-delete-hook
  labels: {{ include "labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": post-delete
    "helm.sh/hook-weight": "0"
    "helm.sh/hook-delete-policy": hook-succeeded
rules:
  - apiGroups:
      - multicluster.admiralty.io
    resources:
      - nodepools
    verbs:
      - list
      - update # TODO replace by patch when we upgrade controller-runtime
  - apiGroups:
      - ""
    resources:
      - pods
      - services
      - nodes
      - endpoints
      - replicasets
      - persistentvolumes
      - persistentvolumeclaims
      - replicationcontrollers
    verbs:
      - list
      - patch
  - apiGroups:
      - apps
    resources:
      - replicasets
      - statefulsets
    verbs:
      - list
      - patch
  - apiGroups:
      - policy
    resources:
      - poddisruptionbudgets
    verbs:
      - list
      - patch
  - apiGroups:
      - storage.k8s.io
    resources:
      - storageclasses
    verbs:
      - list
      - patch
