apiVersion: apps/v1
kind: Deployment
metadata:
  name: multicluster-scheduler
  labels:
    app: multicluster-scheduler
spec:
  selector:
    matchLabels:
      app: multicluster-scheduler
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: multicluster-scheduler
    spec:
      containers:
      - image: quay.io/admiralty/multicluster-scheduler-basic
        imagePullPolicy: Always
        name: controller
        resources:
          limits:
            cpu: 100m
            memory: 60Mi
          requests:
            cpu: 100m
            memory: 40Mi
        securityContext:
          runAsUser: 1000
      serviceAccountName: multicluster-scheduler
      terminationGracePeriodSeconds: 10
