apiVersion: v1
kind: ServiceAccount
metadata:
  name: multicluster-scheduler
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: multicluster-scheduler
rules:
- apiGroups:
  - "multicluster.admiralty.io"
  resources:
  - poddecisions
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
# TODO: less verbs?
- apiGroups:
  - "multicluster.admiralty.io"
  resources:
  - podobservations
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
# TODO: less verbs?
- apiGroups:
  - "multicluster.admiralty.io"
  resources:
  - nodeobservations
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
# TODO: less verbs?
- apiGroups:
  - "multicluster.admiralty.io"
  resources:
  - nodepoolobservations
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
# TODO: less verbs?
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: multicluster-scheduler
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: multicluster-scheduler
subjects:
- kind: ServiceAccount
  name: multicluster-scheduler
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: multicluster-scheduler-member
rules:
- apiGroups:
  - "multicluster.admiralty.io"
  resources:
  - poddecisions
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
# TODO: less verbs?
- apiGroups:
  - "multicluster.admiralty.io"
  resources:
  - podobservations
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
# TODO: less verbs?
- apiGroups:
  - "multicluster.admiralty.io"
  resources:
  - nodeobservations
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
# TODO: less verbs?
- apiGroups:
  - "multicluster.admiralty.io"
  resources:
  - nodepoolobservations
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
# TODO: less verbs?
