apiVersion: skaffold/v1alpha2
kind: Config
build:
  tagPolicy:
    envTemplate:
      template: "{{.IMAGE_NAME}}:{{.RELEASE}}"
  artifacts:
  - imageName: quay.io/admiralty/multicluster-scheduler-basic
    docker:
      dockerfilePath: config/Dockerfile
      buildArgs:
        target: cmd/scheduler
deploy:
  kustomize: {}
