apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "fullname" . }}
  labels: {{ include "labels" . | nindent 4 }}
data:
  config: |
    apiVersion: config.admiralty.io/v1alpha2
    kind: Scheduler
    clusters:
          {{- range .Values.clusters }}
      - name: {{ .name | required "a cluster must have a name" }}
        kubeconfig: /var/run/secrets/admiralty.io/serviceaccountimports/{{ .serviceAccountImportName | default .secretName | default .name }}/config
          {{- if .context }}
        context: {{ .context }}
          {{- end }}
          {{- end }}
