apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "fullname" . }}
  labels: {{ include "labels" . | nindent 4 }}
data:
  config: |
    apiVersion: config.admiralty.io/v1alpha2
    kind: Agent
    webhook:
      port: {{ .Values.webhook.port }}
      certDir: {{ .Values.webhook.certDir }}
