apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "fullname" . }}
  labels: {{ include "labels" . | nindent 4 }}
rules:
  - apiGroups:
      - multicluster.admiralty.io
    resources:
      - nodepools
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - delete
  - apiGroups:
      - ""
    resources:
      - nodes
    verbs:
      - get
      - list
      - watch
      - create # vk
      - update
      - delete
  - apiGroups:
      - ""
    resources:
      - nodes/status
    verbs:
      - patch # vk
  - apiGroups:
      - ""
    resources:
      - services
    verbs:
      - get
      - list
      - watch
      - update
  - apiGroups:
      - ""
    resources:
      - pods
      - endpoints
    verbs:
      - get
      - list
      - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "fullname" . }}-for-scheduler
  labels: {{ include "labels" . | nindent 4 }}
rules:
  - apiGroups:
      - multicluster.admiralty.io
    resources:
      - nodepools
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - ""
    resources:
      - nodes
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - ""
    resources:
      - pods
      - services
    verbs:
      - get
      - list
      - watch
      - update
  - apiGroups:
      - ""
    resources:
      - pods/status
    verbs:
      - update
  - apiGroups:
      - ""
    resources:
      - pods/binding
    verbs:
      - create
  - apiGroups:
      - ""
    resources:
      - "users"
    verbs:
      - "impersonate"
    resourceNames:
            {{- range .Values.invitations }}
      - "admiralty:{{ .clusterName }}"
        {{- end }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "fullname" . }}-for-cluster
  labels: {{ include "labels" . | nindent 4 }}
rules:
  - apiGroups:
      - ""
    resources:
      - pods
      - services
    verbs:
      - create
      - update
      - delete
