apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "fullname" . }}
  labels: {{ include "labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "fullname" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "fullname" . }}
    namespace: {{ .Release.Namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "fullname" . }}-for-scheduler
  labels: {{ include "labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "fullname" . }}-for-scheduler
subjects:
  - kind: ServiceAccount
    name: {{ include "fullname" . }}-for-scheduler
    namespace: {{ .Release.Namespace }}
          {{- range .Values.invitations }}
        {{- if not .namespaces }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "fullname" $ }}-for-{{ .clusterName | required "invited cluster must have a name" }}
  labels: {{ include "labels" $ | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "fullname" $ }}-for-cluster
subjects:
  - kind: User
    name: "admiralty:{{ .clusterName }}"
            {{- end }}
        {{- end }}
