{{- range .Values.invitations }}
        {{- $clusterName := .clusterName }}
        {{- range .namespaces }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "fullname" $ }}-for-{{ $clusterName | required "invited cluster must have a name" }}
  namespace: {{ . }}
  labels: {{ include "labels" $ | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "fullname" $ }}-for-cluster
subjects:
  - kind: User
    name: "admiralty:{{ $clusterName }}"
            {{- end }}
        {{- end }}
