apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "fullname" . }}
  labels: {{ include "labels" . | nindent 4 }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "fullname" . }}-for-scheduler
  labels: {{ include "labels" . | nindent 4 }}
