{{- if not .Values.global.debug }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "fullname" . }}
  labels: {{ include "labels" . | nindent 4 }}
spec:
  selector: {{ include "selectorLabels" . | nindent 4 }}
  ports:
    - port: 443
      protocol: TCP
      targetPort: {{ .Values.webhook.port }}
        {{- end }}
