apiVersion: admissionregistration.k8s.io/v1beta1
kind: MutatingWebhookConfiguration
metadata:
  name: {{ include "fullname" . }}
  labels: {{ include "labels" . | nindent 4 }}
  annotations:
    cert-manager.io/inject-ca-from: {{ .Release.Namespace }}/{{ include "fullname" . }}
webhooks:
  - clientConfig:
      caBundle: Cg==
      service:
        name: {{ include "fullname" . }}
        namespace: {{ .Release.Namespace }}
        path: /mutate-v1-pod
    failurePolicy: Fail
    name: {{ include "fullname" . }}.multicluster.admiralty.io
    namespaceSelector:
      matchLabels:
        multicluster-scheduler: enabled
    rules:
      - apiGroups:
          - ""
        apiVersions:
          - v1
        operations:
          - CREATE
        resources:
          - pods
        scope: '*'
    sideEffects: None
