apiVersion: v1
kind: ServiceAccount
metadata:
  name: multicluster-scheduler-agent
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: multicluster-scheduler-agent
rules:
- apiGroups:
  - "multicluster.admiralty.io"
  resources:
  - multiclusterdeployments
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
# TODO: less verbs?
- apiGroups:
  - "multicluster.admiralty.io"
  resources:
  - nodepools
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
# TODO: less verbs?
- apiGroups:
  - "apps"
  resources:
  - deployments
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
# TODO: less verbs?
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - get
  - list
  - watch
# TODO: less verbs?
- apiGroups:
  - ""
  resources:
  - nodes
  verbs:
  - get
  - list
  - watch
  - update
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: multicluster-scheduler-agent
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: multicluster-scheduler-agent
subjects:
- kind: ServiceAccount
  name: multicluster-scheduler-agent
