apiVersion: skaffold/v1alpha2
kind: Config
build:
  tagPolicy:
    envTemplate:
      template: "{{.IMAGE_NAME}}:{{.RELEASE}}"
  artifacts:
  - imageName: quay.io/admiralty/multicluster-scheduler-agent
    workspace: _out
    docker:
      buildArgs:
        target: cmd/agent
  - imageName: quay.io/admiralty/multicluster-scheduler-pod-admission-controller
    workspace: _out
    docker:
      buildArgs:
        target: cmd/pod-admission-controller
  - imageName: quay.io/admiralty/multicluster-scheduler-basic
    workspace: _out
    docker:
      buildArgs:
        target: cmd/scheduler
deploy:
  kubectl: {}
