apiVersion: skaffold/v1alpha2
kind: Config
build:
  tagPolicy:
    envTemplate:
      template: "{{.IMAGE_NAME}}:{{.RELEASE}}"
  artifacts:
  - imageName: quay.io/admiralty/multicluster-scheduler-agent
    docker:
      dockerfilePath: config/Dockerfile
      buildArgs:
        target: cmd/agent
  - imageName: quay.io/admiralty/multicluster-scheduler-pod-admission-controller
    docker:
      dockerfilePath: config/Dockerfile
      buildArgs:
        target: cmd/pod-admission-controller
  - imageName: quay.io/admiralty/multicluster-scheduler-basic
    docker:
      dockerfilePath: config/Dockerfile
      buildArgs:
        target: cmd/scheduler
deploy:
  kubectl: {}
