apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: poddisruptionbudgetobservations.multicluster.admiralty.io
spec:
  group: multicluster.admiralty.io
  names:
    categories:
      - observations
      - observation
      - obs
    kind: PodDisruptionBudgetObservation
    plural: poddisruptionbudgetobservations
    shortNames:
      - poddisruptionbudgetobs
      - pdbobs
  scope: Namespaced
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          type: string
        kind:
          type: string
        metadata:
          type: object
        spec:
          type: object
        status:
          properties:
            liveState:
              type: object
          type: object
  version: v1alpha1
