global:
  nameOverride: ""
  fullnameOverride: ""
  debug: false

  postDeleteJob:
    image:
      repository: "quay.io/admiralty/multicluster-scheduler-remove-finalizers"
      tag: "" # (default: .Values.global.chart.appVersion)
    #  pullPolicy: IfNotPresent
    #  pullSecretName: ""
    nodeSelector: {}
    resources: {}
    # We usually recommend not to specify default resources and to leave this as a conscious
    # choice for the user. This also increases chances charts run on environments with little
    # resources, such as Minikube. If you do want to specify resources, uncomment the following
    # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
    # limits:
    #   cpu: 100m
    #   memory: 128Mi
    # requests:
    #   cpu: 100m
    #   memory: 128Mi
    securityContext: {}
    # capabilities:
    #   drop:
    #   - ALL
    # readOnlyRootFilesystem: true
    # runAsNonRoot: true
    affinity: {}
    tolerations: []

  # HACK .Chart isn't passed down to child charts
  # so we cherry-pick the fields that they need as globals
  # User, DO NOT override!
  chart:
    name: multicluster-scheduler
    version: "0.7.0"
    appVersion: "0.7.0"

agent:
  enabled: false
  # see subchart's values.yaml for additional variables

scheduler:
  enabled: false
