apiVersion: v1
kind: ServiceAccount
metadata:
  name: CLUSTER_NAME
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: CLUSTER_NAME
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: multicluster-scheduler-member
subjects:
- kind: ServiceAccount
  name: CLUSTER_NAME
