apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "fullname" . }}
  labels: {{ include "labels" . | nindent 4 }}
data:
  config: |
    apiVersion: config.admiralty.io/v1alpha3
    kind: Agent
    webhook:
      port: {{ .Values.webhook.port }}
      certDir: {{ .Values.webhook.certDir }}
    clusterName: {{ .Values.clusterName | required "missing cluster name" }}
    targetSelf: {{ .Values.targetSelf }}
    targets:
          {{- range .Values.targets }}
      - name: {{ .name | required "a target must have a name" }}
        kubeconfig: /var/run/secrets/admiralty.io/serviceaccountimports/{{ .serviceAccountImportName | default .secretName | default .name }}/config
    {{- if .context }}
        context: {{ .context | default "" }}
    {{- end }}
        namespaced: {{ .namespaced | default false }}
          {{- end }}
  proxy-scheduler-config: |
    apiVersion: kubescheduler.config.k8s.io/v1alpha2
    kind: KubeSchedulerConfiguration
    leaderElection:
      leaderElect: false
    profiles:
      - schedulerName: admiralty-proxy
        plugins:
          filter:
            enabled:
              - name: proxy
          reserve:
            enabled:
              - name: proxy
          preBind:
            enabled:
              - name: proxy
          postBind:
            enabled:
              - name: proxy
        pluginConfig:
          - name: proxy
            args:
              clusterName: {{ .Values.clusterName | required "missing cluster name" }}
              targetSelf: {{ .Values.targetSelf }}
              targets:
                    {{- range .Values.targets }}
                - name: {{ .name | required "a target must have a name" }}
                  kubeconfig: /var/run/secrets/admiralty.io/serviceaccountimports/{{ .serviceAccountImportName | default .secretName | default .name }}/config
                    {{- if .context }}
                  context: {{ .context | default "" }}
                    {{- end }}
                  namespaced: {{ .namespaced | default false }}
                    {{- end }}
  candidate-scheduler-config: |
    apiVersion: kubescheduler.config.k8s.io/v1alpha2
    kind: KubeSchedulerConfiguration
    leaderElection:
      leaderElect: false
    profiles:
      - schedulerName: admiralty-candidate
        plugins:
          preFilter:
            enabled:
              - name: candidate
          reserve:
            enabled:
              - name: candidate
          preBind:
            enabled:
              - name: candidate
