apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "fullname" . }}
  labels: {{ include "labels" . | nindent 4 }}
rules:
  - apiGroups:
      - multicluster.admiralty.io
    resources:
      - podchaperons
    verbs:
      - get
      - list
      - watch
      - update
      - patch
  - apiGroups:
      - multicluster.admiralty.io
    resources:
      - podchaperons/status
    verbs:
      - update
  - apiGroups:
      - ""
    resources:
      - pods
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - delete
  - apiGroups:
      - ""
    resources:
      - pods/status
    verbs:
      - update
  - apiGroups:
      - ""
    resources:
      - services
    verbs:
      - get
      - list
      - watch
      - update
  - apiGroups:
      - ""
    resources:
      - endpoints
      - configmaps
      - secrets
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - multicluster.admiralty.io
    resources:
      - clustersummaries
    verbs:
      - get
      - create
      - update
  - apiGroups:
      - ""
    resources:
      - nodes
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - ""
    resources:
      - nodes/status
    verbs:
      - update
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "fullname" . }}-vk
  labels: {{ include "labels" . | nindent 4 }}
rules:
  - apiGroups:
      - ""
    resources:
      - nodes
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - delete
  - apiGroups:
      - ""
    resources:
      - nodes/status
    verbs:
      - patch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "fullname" . }}-source
  labels: {{ include "labels" . | nindent 4 }}
rules:
  - apiGroups:
      - multicluster.admiralty.io
    resources:
      - podchaperons
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - delete
      - deletecollection
      - patch
  - apiGroups:
      - ""
    resources:
      - services
      - secrets
      - configmaps
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - delete
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "fullname" . }}-restarter
  labels: {{ include "labels" . | nindent 4 }}
rules:
  - apiGroups:
      - multicluster.admiralty.io
    resources:
      - targets
      - clustertargets
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - ""
    resources:
      - pods
    verbs:
      - deletecollection
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "fullname" . }}-cluster-summary-viewer
  labels: {{ include "labels" . | nindent 4 }}
rules:
  - apiGroups:
      - multicluster.admiralty.io
    resources:
      - clustersummaries
    verbs:
      - get
      - list
      - watch
