apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: nodepools.multicluster.admiralty.io
  labels:
    helm.sh/chart: multicluster-scheduler
spec:
  group: multicluster.admiralty.io
  names:
    kind: NodePool
    plural: nodepools
    shortNames:
      - np
  scope: Cluster
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          type: string
        kind:
          type: string
        metadata:
          type: object
        spec:
          properties:
            allocatable:
              type: object
            maxNodeCount:
              format: int32
              type: integer
            minNodeCount:
              format: int32
              type: integer
            price:
              type: object
            selector:
              type: object
          required:
            - minNodeCount
            - maxNodeCount
          type: object
        status:
          type: object
  version: v1alpha1
