name: Continuous Integration

on:
  push:
    branches: [ master, setup-ci ]
    paths-ignore:
      - 'docs/**'
  pull_request:
    branches: [ master ]
    paths-ignore:
      - 'docs/**'

jobs:

  build:
    name: All
    runs-on: ubuntu-latest
    steps:

      - name: Set up Go 1.x
        uses: actions/setup-go@v2
        with:
          go-version: ^1.13
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: Get dependencies
        run: go get -v -t -d ./...

      - name: Verify code gen, go vet, go test
        run: ./test/test.sh

      - name: Install Docker
        run: ./build/install_docker.sh

      - name: go build, docker build
        run: VERSION=$GITHUB_SHA ./build/build.sh

      - name: Install kubectl, helm, kind
        run: ./test/e2e/install_dependencies.sh

      - name: End-to-end test
        run: VERSION=$GITHUB_SHA ./test/e2e/e2e.sh

      - name: Archive cluster dump
        if: ${{ failure() }}
        uses: actions/upload-artifact@v1
        with:
          name: cluster-dump
          path: cluster-dump
