name: Go

on:
  push:
    branches: [ master, setup-ci ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

      - name: Set up Go 1.x
        uses: actions/setup-go@v2
        with:
          go-version: ^1.13
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: Get dependencies
        run: go get -v -t -d ./...

      - name: Verify code gen, vet, unit test
        run: ./test/test.sh

      - name: Install Docker
        run: ./build/install_docker.sh

      - name: Build with Go and Docker
        run: ./build/build.sh $GITHUB_SHA

      - name: Install E2E dependencies
        run: ./test/e2e/install_dependencies.sh

      - name: End-to-end test
        run: ./test/e2e/e2e.sh $GITHUB_SHA
